export const Products = [

  {
    id: 1,
    title: "Damascus Hunter",
    price: 540,
    description: "1095/15n20   Elm/Resin Hybrid   Brass Pins",
    category: "Pocket Knives",
    image: require("./images/hunterPocketKnife.png"),
    rating: { rate: 4.75, count: 11 },
  },
  {
    id: 2,
    title: "Bowie Knife",
    price: 400,
    description: "EDC Bowie",
    category: "Pocket Knives",
    image: require("./images/bowiePocketKnife.png"),
    rating: { rate: 4.3, count: 1 },
  },
  {
    id: 3,
    title: "Wisp",
    price: 425,
    description:
      "Ghost Twist Damascus EDC Tanto   15n20/1084 HCS   Black Stabilized Spalted Maple Burl   White Fiber Liners   Natural Canvas   Micarta Liners   Brass Pins",
    category: "Pocket Knives",
    image: require("./images/wispPocketKnife.png"),
    rating: { rate: 3.9, count: 21 },
  },
  {
    id: 4,
    title: "Big Leaf Maple Burl",
    price: 25,
    description: "All in house stabilized and dyed",
    category: "Resin",
    image: require("./images/mapleLeafResin.png"),
    rating: { rate: 4.7, count: 8 },
  },
  {
    id: 5,
    title: "Buckeye Burl",
    price: 25,
    description: "All in house stabilized and dyed",
    category: "Resin",
    image: require("./images/buckeyeResin.png"),
    rating: { rate: 4.4, count: 7 },
  },
  {
    id: 6,
    title: "Redwood Burl",
    price: 50,
    description: "Brown Stabilized Redwood Jeweler’s Lace Burl   5.5”x1.75”x1",
    category: "Resin",
    image: require("./images/redwoodResin.png"),
    rating: { rate: 4.9, count: 4 },
  },
  {
    id: 7,
    title: "Ocean Burl",
    price: 50,
    description: "Stabilized Spalted Maple Burl   7.25”x2.25”x1.75”",
    category: "Resin",
    image: require("./images/oceanResin.png"),
    rating: { rate: 4.7, count: 2 },
  },
  {
    id: 8,
    title: "Kunai",
    price: 700,
    description: "Pair of throwing knives",
    category: "Daggers",
    image: require("./images/kunaiDagger.png"),
    rating: { rate: 4.2, count: 8 },
  },
  {
    id: 9,
    title: "Tolkien",
    price: 800,
    description: "A leaf shaped blade made from 1075/15n20 with a layer of pure nickel. Rough textured mild steel fittings per customers request. Along with a carver purpleheart handle",
    category: "Daggers",
    image: require("./images/tolkienDagger.png"),
    rating: { rate: 5.0, count: 1 },
  },
  {
    id: 10,
    title: "Northland Seax",
    price: 1000,
    description: "Perfect for outdoorsmen   300 layer Damascus   Heirloom fit   Bronze Bolster   Buffalo Horn Spacer   Cherry Handle",
    category: "Swords",
    image: require("./images/seaxSword.png"),
    rating: { rate: 4.9, count: 3 },
  },
  {
    id: 11,
    title: "Heleldr",
    price: 900,
    description: "Elven Short Sword",
    category: "Swords",
    image: require("./images/heleldrSword.png"),
    rating: { rate: 4.7, count: 2 },
  },
  {
    id: 12,
    title: "katana",
    price: 775,
    description: "Small Japanese sword",
    category: "Swords",
    image: require("./images/katanaSword.png"),
    rating: { rate: 4.7, count: 2 },
  },
  {
    id: 13,
    title: "Mjolnir",
    price: 25,
    description: "Mini Thorr hammer decoration",
    category: "Jewelry",
    image: require("./images/mjolnirJewelry.png"),
    rating: { rate: 4.4, count: 10 },
  },
  {
    id: 14,
    title: "Pendant",
    price: 20,
    description: "36 inches soft dark brown leather cord featuring a hand forged iron pendant. Leather cord has a knotted end for variation in lengths",
    category: "Jewelry",
    image: require("./images/pendantJewelry.png"),
    rating: { rate: 4.6, count: 5 },
  },
  {
    id: 15,
    title: "Fanghorn",
    price: 350,
    description: "Curly Maple, Peened Copper Pins. With carvings and engravings (comes with leather sheath w/ulti-clip)",
    category: "Pocket Knives",
    image: require("./images/fanghornPocketKnife.png"),
    rating: { rate: 4.9, count: 3 },
  },
  {
    id: 16,
    title: "Omen",
    price: 405,
    description: "Damascus drop point Go Mai",
    category: "Pocket Knives",
    image: require("./images/omenPocketKnife.png"),
    rating: { rate: 5.0, count: 3 },
  },
  {
    id: 17,
    title: "Swords",
    price: 800,
    description: "Choose From a Variety of Handcrafted Swords",
    category: "Swords",
    image: require("./images/swords.jfif"),
    rating: {rate : 4.8, count: 61},
  },
  {
    id: 18,
    title: "Bronze Dagger",
    price: 250,
    description: "Fully integral dagger made from Alum-Bronze. More of a show piece but still usable",
    category: "Daggers",
    image: require("./images/daggers.png"),
    rating: {rate: 4.5, count : 3},
  },
  {
    id: 19,
    title: "Custom Order",
    price: 900,
    description: "Recieve a compeletely unique piece hand-made to fit your specifications",
    category: "Custom",
    image: require("./images/custom.png"),
    rating: {rate: 4.9, count: 20},
  }
]